### ISSUE TITLE
crash when breaking fan while active/showing area

### ISSUE THREAD

**Issue by LlubNek** [yzl210/MobFarmUtilities#5]
Minecraft crashed when I broke a fan which was both active and showing the affected area.

MobFarmHelpers-1.16.5-1.4.1-forge.jar
forge 36.1.4
MC 1.16.5

[crash-2021-04-07_22.00.42-client.txt](https://github.com/yzl210/MobFarmUtilities/files/6275512/crash-2021-04-07_22.00.42-client.txt)
[latest.log](https://github.com/yzl210/MobFarmUtilities/files/6275515/latest.log)

**Comment by yzl210** [comment]
Can't reproduce it, but I'll try to fix it, thanks for the report!

**Comment by LlubNek** [comment]
happened again
this time it wasn't active, but it was showing the affected area when I broke it.
both times I had upgrades in there.

[crash-2021-04-09_13.51.59-client.txt](https://github.com/yzl210/MobFarmUtilities/files/6287600/crash-2021-04-09_13.51.59-client.txt)
[latest.log](https://github.com/yzl210/MobFarmUtilities/files/6287601/latest.log)

**Comment by yzl210** [comment]
Fixed in 1.4.2
