### ISSUE TITLE
I can't find the dpwmload

### ISSUE THREAD

**Issue by SodiyumChloride** [yzl210/MobFarmUtilities#8]
Hello! I can not seem to find the download, i have tried downloading a ZIP of the mod and try to load it with no avail

**Comment by yzl210** [comment]
Hi! The download is on curseforge, here are the links:
Forge: https://www.curseforge.com/minecraft/mc-mods/mob-farm-helpers-forge
Fabric: https://www.curseforge.com/minecraft/mc-mods/mob-farm-helpers-fabric
