### ISSUE TITLE
Area of effect different depending on direction

### ISSUE THREAD

**Issue by Fourmisain** [yzl210/MobFarmUtilities#9]
Here's 4 fans without any upgrades:
![width0](https://user-images.githubusercontent.com/8464472/122741125-ee45cd00-d284-11eb-8886-abcc75faf1af.png)
The north and west facing ones have an area of 4x1 while the south and east facing ones have an area of 6x1 (including the fan itself).

I now increased the width of each fan:
![width1](https://user-images.githubusercontent.com/8464472/122741129-ef76fa00-d284-11eb-8fcf-6fce022e0135.png)
Note that the south and west facing fans did not actually increase the width despite being upgraded! (It does increase after upgrading it once more.)

Similarly,
downwards facing fans have an area of 4x1, while upwards facing fans have an area of 6x1 (including the fan).
Their width increases correctly, but their height does not.

**Comment by yzl210** [comment]
I'll look into that

**Comment by yzl210** [comment]
Fixed in 29c73a7
